/// Telugu translations, keyed by the English string as it appears in the UI.
///
/// Same contract as [hindiStrings]: prose only. Amounts, dates, percentages and
/// account numbers stay in Latin numerals, and every screen that formats a
/// number interpolates it, so those strings never reach this map.
///
/// Telugu is the tightest fit of the three scripts — its glyphs carry stacked
/// vowel and consonant marks, so a line box is taller than Latin at the same
/// point size and compound words run long. Labels that sit in bottom-nav items,
/// pills and table headers are therefore kept as short as the meaning allows.
const Map<String, String> teluguStrings = {
  // ─── Navigation and common actions ────────────────────────────────────
  'Home': 'హోమ్',
  'Goals': 'లక్ష్యాలు',
  'Portfolio': 'పోర్ట్‌ఫోలియో',
  'Insights': 'సమాచారం',
  'Settings': 'సెట్టింగ్‌లు',
  'Cancel': 'రద్దు',
  'Save': 'సేవ్',
  'Done': 'పూర్తయింది',
  'Continue': 'కొనసాగించు',
  'Close': 'మూసివేయి',
  'Clear': 'తొలగించు',
  'Manage': 'నిర్వహణ',
  'Got it': 'అర్థమైంది',
  'See all': 'అన్నీ చూడు',
  'View all →': 'అన్నీ చూడు →',
  'Details →': 'వివరాలు →',
  'Manage →': 'నిర్వహణ →',
  'Documents →': 'పత్రాలు →',
  'Coverage →': 'కవరేజ్ →',
  'Statements →': 'వివరాలు →',
  'Full history →': 'పూర్తి చరిత్ర →',
  'All news →': 'అన్ని వార్తలు →',
  'Verified': 'ధృవీకరించబడింది',
  'VERIFIED': 'ధృవీకరించబడింది',
  'LIVE': 'లైవ్',
  'Live': 'లైవ్',
  'ACTIVE': 'యాక్టివ్',
  'Just now': 'ఇప్పుడే',
  'Recent': 'ఇటీవలి',
  'TOTAL': 'మొత్తం',
  'Category': 'వర్గం',
  'CATEGORY': 'వర్గం',
  'Description': 'వివరణ',
  'AMOUNT': 'మొత్తం',
  'Deposit': 'జమ',
  'Excellent': 'అద్భుతం',
  'All Clear': 'అంతా బాగుంది',
  'ON TIME': 'సమయానికి',
  'Fill': 'నింపు',
  'Log': 'లాగ్',
  'Policy': 'పాలసీ',
  'Goal': 'లక్ష్యం',
  'SYMBOL': 'చిహ్నం',
  'ON RECORD': 'రికార్డులో',
  'AVAILABLE': 'అందుబాటులో',
  'REFERENCE': 'సూచన',
  'CASE ID': 'కేస్ ఐడీ',
  'Evidence': 'ఆధారం',
  'Under Review': 'సమీక్షలో',
  'FINIX App': 'ఫినిక్స్ యాప్',
  'REPORTED ON': 'నివేదిక తేదీ',
  'REPORTED VIA': 'నివేదిక మార్గం',

  // ─── Dashboard ────────────────────────────────────────────────────────
  'TOTAL NET WORTH': 'మొత్తం నికర ఆస్తి',
  'View Portfolio': 'పోర్ట్‌ఫోలియో చూడు',
  'All Accounts': 'అన్ని ఖాతాలు',
  'Quick Actions': 'త్వరిత చర్యలు',
  'Quick actions': 'త్వరిత చర్యలు',
  'Overview': 'సమగ్ర వీక్షణ',
  'Spent this month': 'ఈ నెల ఖర్చు',
  'No prior month': 'గత నెల లేదు',
  'Asset Allocation': 'ఆస్తుల కేటాయింపు',
  'No holdings': 'హోల్డింగ్‌లు లేవు',
  'Goals Progress': 'లక్ష్యాల పురోగతి',
  'Credit Score': 'క్రెడిట్ స్కోర్',
  'Upcoming commitments': 'రాబోయే చెల్లింపులు',
  'Nothing scheduled': 'ఏమీ షెడ్యూల్ కాలేదు',
  'Protection': 'రక్షణ',
  'Market Snapshot': 'మార్కెట్ సంగ్రహం',
  'See full analysis': 'పూర్తి విశ్లేషణ చూడు',
  'Recent Activity': 'ఇటీవలి కార్యకలాపం',
  'FINIX INSIGHT': 'ఫినిక్స్ సమాచారం',
  'Health Score': 'ఆరోగ్య స్కోర్',
  'About Health Score': 'ఆరోగ్య స్కోర్ గురించి',

  // ─── Payments ─────────────────────────────────────────────────────────
  'Pay Anyone': 'ఎవరికైనా చెల్లించు',
  'Pay to Contact': 'కాంటాక్ట్‌కు చెల్లించు',
  'Pay to Merchant': 'వ్యాపారికి చెల్లించు',
  'Pay Now': 'చెల్లించు',
  'Pay Securely →': 'సురక్షిత చెల్లింపు →',
  'ENTER AMOUNT': 'మొత్తం నమోదు చేయి',
  'Scan QR': 'క్యూఆర్ స్కాన్',
  'Align the QR code within the frame': 'క్యూఆర్ కోడ్‌ను ఫ్రేమ్‌లో ఉంచండి',
  'Payment Successful': 'చెల్లింపు విజయవంతం',
  'Back to Home': 'హోమ్‌కు తిరిగి',
  'Transaction Successful': 'లావాదేవీ విజయవంతం',
  'Authorising Transaction...': 'లావాదేవీ ఆమోదం పొందుతోంది...',
  'Secure encryption active': 'సురక్షిత ఎన్‌క్రిప్షన్ చురుకుగా ఉంది',
  'Transaction History': 'లావాదేవీల చరిత్ర',
  'No Transactions Found': 'లావాదేవీలు కనుగొనబడలేదు',
  'Bank transfer': 'బ్యాంక్ బదిలీ',
  'Secure Ledger Transfer': 'సురక్షిత లెడ్జర్ బదిలీ',
  'Verified by FINIX Protocol': 'ఫినిక్స్ ప్రోటోకాల్ ధృవీకరణ',
  'Please enter a valid payment amount.': 'దయచేసి సరైన మొత్తాన్ని నమోదు చేయండి.',
  'BANK ACCOUNT NUMBER': 'బ్యాంక్ ఖాతా సంఖ్య',
  'IFSC CODE': 'ఐఎఫ్‌ఎస్‌సీ కోడ్',
  'Recent transfers': 'ఇటీవలి బదిలీలు',
  'No recent transfers yet': 'ఇంకా బదిలీలు లేవు',
  'Transfer to Self': 'మీ ఖాతాకు బదిలీ',
  'Transfer Now': 'ఇప్పుడే బదిలీ చేయి',
  'Between your accounts': 'మీ ఖాతాల మధ్య',
  'Link a second account': 'రెండో ఖాతా జోడించు',
  'Instant transfer · No charges': 'తక్షణ బదిలీ · ఛార్జీలు లేవు',
  'Recent Searches': 'ఇటీవలి శోధనలు',
  'Search for IFSC': 'ఐఎఫ్‌ఎస్‌సీ శోధించు',
  'No banks found.': 'బ్యాంకులు కనుగొనబడలేదు.',

  // ─── Accounts ─────────────────────────────────────────────────────────
  'Linked Accounts': 'అనుసంధాన ఖాతాలు',
  'Add Account': 'ఖాతా జోడించు',
  'No linked accounts yet': 'ఇంకా ఖాతాలు జోడించలేదు',
  'Link a bank above to see balances here.':
      'బ్యాలెన్స్ చూడటానికి పైన బ్యాంక్ జోడించండి.',
  'TOTAL COMBINED BALANCE': 'మొత్తం కలిపిన బ్యాలెన్స్',
  '+ Link a new account': '+ కొత్త ఖాతా జోడించు',
  'ACCOUNT AGGREGATOR': 'ఖాతా అగ్రిగేటర్',
  'Last sync: ': 'చివరి సింక్: ',
  'LINKED DETAILS': 'అనుసంధాన వివరాలు',
  'Linking your account': 'మీ ఖాతా జోడించబడుతోంది',
  'successfully!': 'విజయవంతంగా!',

  // ─── Goals ────────────────────────────────────────────────────────────
  'No goals yet': 'ఇంకా లక్ష్యాలు లేవు',
  'Add a goal above to start tracking progress.':
      'పురోగతి చూడటానికి పైన లక్ష్యం జోడించండి.',
  'TOTAL GOAL SAVINGS': 'మొత్తం లక్ష్య పొదుపు',
  'Add new goal': 'కొత్త లక్ష్యం',
  'New Goal': 'కొత్త లక్ష్యం',
  'Create goal': 'లక్ష్యం సృష్టించు',
  'GOAL NAME': 'లక్ష్యం పేరు',
  'TARGET AMOUNT': 'లక్ష్య మొత్తం',
  'BY WHEN': 'ఎప్పటిలోగా',
  'Please enter a goal name.': 'దయచేసి లక్ష్యం పేరు నమోదు చేయండి.',
  'Add Money to Goal': 'లక్ష్యానికి డబ్బు జోడించు',
  'Add money': 'డబ్బు జోడించు',
  'Milestones': 'మైలురాళ్ళు',
  'Linked sources': 'అనుసంధాన మూలాలు',
  'No contribution plan set for this goal.':
      'ఈ లక్ష్యానికి సహకార ప్రణాళిక లేదు.',
  'Run What-If': 'ఏమైతే చూడు',
  'Run What-If →': 'ఏమైతే చూడు →',

  // ─── Portfolio, loans, insurance ──────────────────────────────────────
  'Portfolio Hub': 'పోర్ట్‌ఫోలియో కేంద్రం',
  'Manage your wealth': 'మీ సంపదను నిర్వహించండి',
  'TOTAL PORTFOLIO VALUE': 'మొత్తం పోర్ట్‌ఫోలియో విలువ',
  'Investments': 'పెట్టుబడులు',
  'Loans': 'రుణాలు',
  'Active loans': 'చురుకైన రుణాలు',
  'No active loans': 'చురుకైన రుణాలు లేవు',
  'TOTAL OUTSTANDING': 'మొత్తం బకాయి',
  'Next payment': 'తదుపరి చెల్లింపు',
  'Recent EMIs': 'ఇటీవలి ఈఎంఐలు',
  'Loan Statement': 'రుణ వివరణ',
  'HOME LOAN · OUTSTANDING': 'గృహ రుణం · బకాయి',
  'Download full statement (PDF)': 'పూర్తి వివరణ డౌన్‌లోడ్ (పీడీఎఫ్)',
  'Insurance': 'బీమా',
  'Your policies': 'మీ పాలసీలు',
  'No active policies': 'చురుకైన పాలసీలు లేవు',
  'Coverage analysis': 'కవరేజ్ విశ్లేషణ',
  'Coverage Analysis': 'కవరేజ్ విశ్లేషణ',
  'Current cover': 'ప్రస్తుత కవర్',
  'Suggested cover': 'సూచించిన కవర్',
  'COVERAGE GAP': 'కవరేజ్ అంతరం',
  'Protection Report': 'రక్షణ నివేదిక',
  'Full protection report →': 'పూర్తి రక్షణ నివేదిక →',
  'FINIX PROTECTION SCORE': 'ఫినిక్స్ రక్షణ స్కోర్',
  'File a Claim': 'క్లెయిమ్ దాఖలు చేయి',
  'Which policy': 'ఏ పాలసీ',
  'Claim type': 'క్లెయిమ్ రకం',
  'Claim amount': 'క్లెయిమ్ మొత్తం',
  'Submit claim': 'క్లెయిమ్ సమర్పించు',
  'Upload bills & discharge summary': 'బిల్లులు, డిశ్చార్జ్ సారాంశం అప్‌లోడ్',
  'See suggested plans →': 'సూచించిన ప్లాన్‌లు చూడు →',

  // ─── Markets ──────────────────────────────────────────────────────────
  'Markets': 'మార్కెట్లు',
  'MARKET OVERVIEW': 'మార్కెట్ సమగ్ర వీక్షణ',
  'YOUR PORTFOLIO TODAY': 'నేడు మీ పోర్ట్‌ఫోలియో',
  'Market pulse': 'మార్కెట్ స్పందన',
  'Market Pulse Details': 'మార్కెట్ స్పందన వివరాలు',
  'Sector performance': 'రంగాల పనితీరు',
  'Sector Performance': 'రంగాల పనితీరు',
  'Top movers': 'ప్రధాన కదలికలు',
  'Top Movers': 'ప్రధాన కదలికలు',
  'Market Movers': 'మార్కెట్ కదలికలు',
  'Top AI insights': 'ప్రధాన ఏఐ సమాచారం',
  'Market news': 'మార్కెట్ వార్తలు',

  // ─── Tax ──────────────────────────────────────────────────────────────
  'Tax Centre': 'పన్ను కేంద్రం',
  'Old Regime': 'పాత విధానం',
  'New Regime': 'కొత్త విధానం',
  'Old regime': 'పాత విధానం',
  'New regime': 'కొత్త విధానం',
  'BETTER FOR YOU': 'మీకు మెరుగైనది',
  'Regime Comparison': 'విధానాల పోలిక',
  'ESTIMATED SAVING': 'అంచనా పొదుపు',
  'OLD REGIME': 'పాత విధానం',
  'NEW REGIME': 'కొత్త విధానం',
  'Deduction sections': 'మినహాయింపు విభాగాలు',
  'No deductions · Lower slabs': 'మినహాయింపులు లేవు · తక్కువ శ్లాబ్‌లు',
  'No deductions recorded for this year':
      'ఈ సంవత్సరం మినహాయింపులు నమోదు కాలేదు',
  'Apply new regime →': 'కొత్త విధానం వర్తింపజేయి →',
  'New regime applied successfully!': 'కొత్త విధానం విజయవంతంగా వర్తించింది!',
  'Add Proof': 'ఆధారం జోడించు',
  '+ Upload a proof': '+ ఆధారం అప్‌లోడ్ చేయి',
  'Upload Proof Document': 'ఆధార పత్రం అప్‌లోడ్ చేయి',
  'Take Photo / Scan': 'ఫోటో తీయి / స్కాన్ చేయి',
  'Upload PDF / Document': 'పీడీఎఫ్ / పత్రం అప్‌లోడ్ చేయి',
  'Uploading File': 'ఫైల్ అప్‌లోడ్ అవుతోంది',
  'Uploaded successfully • verified by AI':
      'విజయవంతంగా అప్‌లోడ్ • ఏఐ ధృవీకరణ',

  // ─── Security ─────────────────────────────────────────────────────────
  'Security': 'భద్రత',
  'YOUR ACCOUNT': 'మీ ఖాతా',
  'Protection tools': 'రక్షణ సాధనాలు',
  'Protection score · ': 'రక్షణ స్కోర్ · ',
  'Threats blocked · ': 'నిరోధించిన ముప్పులు · ',
  'Last scan · ': 'చివరి స్కాన్ · ',
  'Recent activity': 'ఇటీవలి కార్యకలాపం',
  'Security Events': 'భద్రతా ఘటనలు',
  'Emergency Freeze': 'అత్యవసర ఫ్రీజ్',
  'Freeze Account': 'ఖాతా ఫ్రీజ్ చేయి',
  'Activate Emergency Freeze?': 'అత్యవసర ఫ్రీజ్ చేయాలా?',
  'ACCOUNT FROZEN': 'ఖాతా ఫ్రీజ్ చేయబడింది',
  'Unlock with Biometrics': 'బయోమెట్రిక్‌తో అన్‌లాక్ చేయి',
  'Cancel — keep accounts active': 'రద్దు — ఖాతాలు చురుకుగా ఉంచు',
  'SLIDE TO FREEZE ALL': 'అన్నీ ఫ్రీజ్ చేయడానికి స్లైడ్ చేయి',
  'WHAT HAPPENS WHEN YOU FREEZE': 'ఫ్రీజ్ చేస్తే ఏమి జరుగుతుంది',
  'This will instantly halt all outgoing transactions\nacross every linked account.':
      'ఇది ప్రతి అనుసంధాన ఖాతా నుండి బయటకు వెళ్ళే\nలావాదేవీలను తక్షణమే నిలిపివేస్తుంది.',
  'SMS Detector': 'ఎస్‌ఎంఎస్ డిటెక్టర్',
  'Scan now': 'స్కాన్ చేయి',
  'RECENT SCANS': 'ఇటీవలి స్కాన్‌లు',
  'Checking latest inbox messages locally...':
      'ఇన్‌బాక్స్ సందేశాలు పరికరంలో తనిఖీ అవుతున్నాయి...',
  'No messages in your inbox to scan.':
      'స్కాన్ చేయడానికి ఇన్‌బాక్స్‌లో సందేశాలు లేవు.',
  'FINIX Security Suite': 'ఫినిక్స్ భద్రతా సూట్',
  'Fingerprint not recognised — nothing was changed.':
      'వేలిముద్ర గుర్తించబడలేదు — ఏమీ మారలేదు.',
  'Account unlocked successfully.': 'ఖాతా విజయవంతంగా అన్‌లాక్ అయింది.',
  'All security protections activated!': 'అన్ని భద్రతలు చురుకుగా మారాయి!',
  'Audit Logs': 'ఆడిట్ లాగ్‌లు',
  'MERKLE-VERIFIED': 'మెర్కిల్-ధృవీకరణ',
  'No audit events recorded yet.': 'ఇంకా ఆడిట్ ఘటనలు నమోదు కాలేదు.',
  'Ledger database is up to date.': 'లెడ్జర్ డేటాబేస్ తాజాగా ఉంది.',
  'Report Fraud': 'మోసం నివేదించు',
  'Report Acknowledged': 'నివేదిక ఆమోదించబడింది',
  'Submit report': 'నివేదిక సమర్పించు',
  'Immediate actions taken': 'తక్షణ చర్యలు తీసుకోబడ్డాయి',
  'What happens next': 'తరువాత ఏమి జరుగుతుంది',
  'Attached successfully': 'విజయవంతంగా జతచేయబడింది',
  'Upload screenshot or receipt': 'స్క్రీన్‌షాట్ లేదా రసీదు అప్‌లోడ్ చేయి',
  'Upload Evidence File': 'ఆధార ఫైల్ అప్‌లోడ్ చేయి',
  'Take Photo / Screenshot': 'ఫోటో / స్క్రీన్‌షాట్ తీయి',
  'Upload PDF / Statement': 'పీడీఎఫ్ / వివరణ అప్‌లోడ్ చేయి',
  'Attaching Evidence': 'ఆధారం జతచేయబడుతోంది',

  // ─── Notifications ────────────────────────────────────────────────────
  'Notifications': 'నోటిఫికేషన్‌లు',
  'All caught up!': 'అన్నీ చూశారు!',
  'No new notifications for you right now.':
      'ప్రస్తుతం మీకు కొత్త నోటిఫికేషన్‌లు లేవు.',
  'Reset Notifications': 'నోటిఫికేషన్‌లు రీసెట్ చేయి',

  // ─── Profile and settings ─────────────────────────────────────────────
  'Personal details': 'వ్యక్తిగత వివరాలు',
  'Update Nominee': 'నామినీ నవీకరించు',
  'Current nominee': 'ప్రస్తుత నామినీ',
  'New nominee details': 'కొత్త నామినీ వివరాలు',
  'Save nominee': 'నామినీ సేవ్ చేయి',
  'Select Relationship': 'సంబంధం ఎంచుకో',
  'KYC VERIFIED': 'కేవైసీ ధృవీకరణ',
  'Sign out': 'సైన్ అవుట్',
  'Sign out?': 'సైన్ అవుట్?',
  'You will need your cKYC number and PIN to sign back in.':
      'మళ్ళీ సైన్ ఇన్ కావడానికి మీ సీకేవైసీ నంబర్, పిన్ అవసరం.',
  'eKYC completed': 'ఈ-కేవైసీ పూర్తయింది',
  'Last profile change': 'చివరి ప్రొఫైల్ మార్పు',
  'Request a correction': 'సవరణ కోరండి',
  'Documents': 'పత్రాలు',
  'No documents found': 'పత్రాలు కనుగొనబడలేదు',
  'Download all as ZIP': 'అన్నీ జిప్‌గా డౌన్‌లోడ్ చేయి',
  'Help & FAQs tapped': 'సహాయం',

  // ─── Sign in and eKYC ─────────────────────────────────────────────────
  'Sign in to FINIX': 'ఫినిక్స్‌లో సైన్ ఇన్ చేయి',
  'Sign in': 'సైన్ ఇన్',
  'New to FINIX?  ': 'ఫినిక్స్‌కు కొత్తా?  ',
  'Complete eKYC': 'ఈ-కేవైసీ పూర్తి చేయి',
  'Continue to eKYC': 'ఈ-కేవైసీ కొనసాగించు',
  'Forgot PIN?': 'పిన్ మర్చిపోయారా?',
  'API address': 'ఏపీఐ చిరునామా',
  'Why complete eKYC?': 'ఈ-కేవైసీ ఎందుకు?',
  'Verify CKYC Number': 'సీకేవైసీ నంబర్ ధృవీకరించు',
  'CKYC NUMBER / KIN': 'సీకేవైసీ నంబర్ / కేఐఎన్',
  'Start Authentication': 'ప్రామాణీకరణ ప్రారంభించు',
  'API SLOT': 'ఏపీఐ స్లాట్',
  'Ready for bank API integration': 'బ్యాంక్ ఏపీఐ అనుసంధానానికి సిద్ధం',
  'Your information is processed securely, only with your consent.':
      'మీ సమాచారం మీ సమ్మతితో మాత్రమే, సురక్షితంగా ప్రాసెస్ చేయబడుతుంది.',
  'eKYC Verification Completed Successfully!':
      'ఈ-కేవైసీ ధృవీకరణ విజయవంతంగా పూర్తయింది!',
  'Your session expired. Please sign in again.':
      'మీ సెషన్ ముగిసింది. దయచేసి మళ్ళీ సైన్ ఇన్ చేయండి.',

  // ─── Simulation ───────────────────────────────────────────────────────
  'Run simulation': 'సిమ్యులేషన్ నడుపు',
  'Run simulation →': 'సిమ్యులేషన్ నడుపు →',
  'Run a simulation': 'సిమ్యులేషన్ నడుపు',
  'Simulation Completed': 'సిమ్యులేషన్ పూర్తయింది',
  'Back to Simulation': 'సిమ్యులేషన్‌కు తిరిగి',
  'Apply this change': 'ఈ మార్పు వర్తింపజేయి',
  'What do you want to try?': 'మీరు ఏమి ప్రయత్నించాలనుకుంటున్నారు?',
  'What this changes': 'ఇది ఏమి మారుస్తుంది',
  'How we worked this out': 'మేము దీన్ని ఎలా లెక్కించాము',
  'How this works': 'ఇది ఎలా పనిచేస్తుంది',
  'Why we say this': 'మేము ఇలా ఎందుకు చెబుతున్నాము',
  'EXTRA EACH MONTH': 'ప్రతి నెల అదనంగా',
  'FOR HOW LONG': 'ఎంత కాలం',
  'These are projections, not promises': 'ఇవి అంచనాలు, హామీలు కావు',
  'Running compounding projection...': 'చక్రవడ్డీ అంచనా నడుస్తోంది...',
  'By area': 'ప్రాంతం వారీగా',
  'Acknowledgement': 'ధృవీకరణ',

  // ─── AI assistant ─────────────────────────────────────────────────────
  'Finix AI': 'ఫినిక్స్ ఏఐ',
  'Ask Finix AI': 'ఫినిక్స్ ఏఐని అడగండి',
  'Online • Wealth Assistant': 'ఆన్‌లైన్ • సంపద సహాయకుడు',

  // ─── Language picker and preferences ──────────────────────────────────
  'Language': 'భాష',
  'Choose your app language': 'మీ యాప్ భాషను ఎంచుకోండి',
  'The app will restart to apply your choice.':
      'మీ ఎంపిక వర్తింపజేయడానికి యాప్ పునఃప్రారంభమవుతుంది.',
  'Restarting to apply the new language…':
      'కొత్త భాష వర్తింపజేయడానికి పునఃప్రారంభమవుతోంది…',
  'Preferences': 'ప్రాధాన్యతలు',
  'Account': 'ఖాతా',
  'Privacy & data': 'గోప్యత, డేటా',
  'Support': 'మద్దతు',
  'Transaction limits': 'లావాదేవీ పరిమితులు',
  'Data sharing consents': 'డేటా భాగస్వామ్య సమ్మతులు',
  'Privacy Policy': 'గోప్యతా విధానం',
  'Terms & conditions': 'నిబంధనలు, షరతులు',
  'Ethical charter': 'నైతిక చార్టర్',
  'Help & FAQs': 'సహాయం',
  'Biometric login': 'బయోమెట్రిక్ లాగిన్',

  // ─── Added: navigation, settings rows and seeded goal names ──────────
  'goals': 'లక్ష్యాలు',
  'portfolio': 'పోర్ట్‌ఫోలియో',
  'chat': 'చాట్',
  'security': 'భద్రత',
  'Dashboard': 'డాష్‌బోర్డ్',
  'Scan & Pay': 'స్కాన్ చెల్లింపు',
  'Transfer': 'బదిలీ',
  'To Contact': 'కాంటాక్ట్‌కు',
  'To Self': 'మీకు',
  'Linked accounts': 'అనుసంధాన ఖాతాలు',
  'Nominees & Trust Circle': 'నామినీలు, విశ్వాస వలయం',
  'Security Corner': 'భద్రతా విభాగం',
  'Audit logs': 'ఆడిట్ లాగ్‌లు',
  'Privacy policy': 'గోప్యతా విధానం',
  'Report fraud': 'మోసం నివేదించు',
  'Data sharing': 'డేటా భాగస్వామ్యం',
  'Help & support': 'సహాయం',
  'Name, PAN, Aadhaar, address': 'పేరు, పాన్, ఆధార్, చిరునామా',
  'Risk gate, SMS scanner, emergency freeze':
      'రిస్క్ గేట్, ఎస్‌ఎంఎస్ స్కానర్, అత్యవసర ఫ్రీజ్',
  'Tamper-evident record of every action':
      'ప్రతి చర్యకు తారుమారు కాని రికార్డు',
  'Risk alerts, goals, market digest':
      'రిస్క్ హెచ్చరికలు, లక్ష్యాలు, మార్కెట్ సారాంశం',
  'Guides, chat with support': 'గైడ్‌లు, మద్దతుతో చాట్',
  'Face ID enrolled on this device': 'ఈ పరికరంలో ఫేస్ ఐడీ నమోదైంది',
  'House Down Payment': 'ఇంటి డౌన్ పేమెంట్',
  'Home Down Payment': 'ఇంటి డౌన్ పేమెంట్',
  'Emergency Fund': 'అత్యవసర నిధి',
  'Europe Trip': 'యూరప్ యాత్ర',
  'Child Education': 'పిల్లల విద్య',
  'Retirement Fund': 'పదవీ విరమణ నిధి',
  'Vehicle Loan': 'వాహన రుణం',
  'Home Loan': 'గృహ రుణం',
  'Ask Finix AI...': 'ఫినిక్స్ ఏఐని అడగండి...',
  'Microphone unavailable. Check app permissions.':
      'మైక్రోఫోన్ అందుబాటులో లేదు. యాప్ అనుమతులు తనిఖీ చేయండి.',
  'Listening…': 'వింటున్నాము…',
};
