/// Hindi translations, keyed by the English string as it appears in the UI.
///
/// Only prose is translated. Amounts, dates, percentages, account numbers and
/// index levels stay in Latin numerals — a customer reading a balance wants
/// "₹1,15,239", not Devanagari digits, and every screen that formats a number
/// interpolates it, so those strings never reach this map.
///
/// Translations are kept deliberately short. Devanagari renders taller and
/// often wider than Latin for the same meaning, and several of these labels sit
/// in fixed-width pills, table headers and bottom-nav items where a longer
/// string would wrap or clip.
const Map<String, String> hindiStrings = {
  // ─── Navigation and common actions ────────────────────────────────────
  'Home': 'होम',
  'Goals': 'लक्ष्य',
  'Portfolio': 'पोर्टफोलियो',
  'Insights': 'जानकारी',
  'Settings': 'सेटिंग्स',
  'Cancel': 'रद्द करें',
  'Save': 'सहेजें',
  'Done': 'हो गया',
  'Continue': 'जारी रखें',
  'Close': 'बंद करें',
  'Clear': 'साफ़ करें',
  'Manage': 'प्रबंधन',
  'Got it': 'समझ गया',
  'See all': 'सभी देखें',
  'View all →': 'सभी देखें →',
  'Details →': 'विवरण →',
  'Manage →': 'प्रबंधन →',
  'Documents →': 'दस्तावेज़ →',
  'Coverage →': 'कवरेज →',
  'Statements →': 'विवरण →',
  'Full history →': 'पूरा इतिहास →',
  'All news →': 'सभी समाचार →',
  'Verified': 'सत्यापित',
  'VERIFIED': 'सत्यापित',
  'LIVE': 'लाइव',
  'Live': 'लाइव',
  'ACTIVE': 'सक्रिय',
  'Just now': 'अभी',
  'Recent': 'हाल के',
  'TOTAL': 'कुल',
  'Category': 'श्रेणी',
  'CATEGORY': 'श्रेणी',
  'Description': 'विवरण',
  'AMOUNT': 'राशि',
  'Deposit': 'जमा',
  'Excellent': 'उत्कृष्ट',
  'All Clear': 'सब ठीक',
  'ON TIME': 'समय पर',
  'Fill': 'भरें',
  'Log': 'लॉग',
  'Policy': 'पॉलिसी',
  'Goal': 'लक्ष्य',
  'SYMBOL': 'प्रतीक',
  'ON RECORD': 'रिकॉर्ड में',
  'AVAILABLE': 'उपलब्ध',
  'REFERENCE': 'संदर्भ',
  'CASE ID': 'केस आईडी',
  'Evidence': 'साक्ष्य',
  'Under Review': 'समीक्षाधीन',
  'FINIX App': 'फिनिक्स ऐप',
  'REPORTED ON': 'रिपोर्ट की तिथि',
  'REPORTED VIA': 'रिपोर्ट का माध्यम',

  // ─── Dashboard ────────────────────────────────────────────────────────
  'TOTAL NET WORTH': 'कुल निवल संपत्ति',
  'View Portfolio': 'पोर्टफोलियो देखें',
  'All Accounts': 'सभी खाते',
  'Quick Actions': 'त्वरित कार्य',
  'Quick actions': 'त्वरित कार्य',
  'Overview': 'अवलोकन',
  'Spent this month': 'इस माह खर्च',
  'No prior month': 'पिछला माह नहीं',
  'Asset Allocation': 'संपत्ति आवंटन',
  'No holdings': 'कोई होल्डिंग नहीं',
  'Goals Progress': 'लक्ष्य प्रगति',
  'Credit Score': 'क्रेडिट स्कोर',
  'Upcoming commitments': 'आगामी भुगतान',
  'Nothing scheduled': 'कुछ निर्धारित नहीं',
  'Protection': 'सुरक्षा',
  'Market Snapshot': 'बाज़ार झलक',
  'See full analysis': 'पूरा विश्लेषण देखें',
  'Recent Activity': 'हाल की गतिविधि',
  'FINIX INSIGHT': 'फिनिक्स अंतर्दृष्टि',
  'Health Score': 'स्वास्थ्य स्कोर',
  'About Health Score': 'स्वास्थ्य स्कोर के बारे में',

  // ─── Payments ─────────────────────────────────────────────────────────
  'Pay Anyone': 'किसी को भुगतान',
  'Pay to Contact': 'संपर्क को भुगतान',
  'Pay to Merchant': 'व्यापारी को भुगतान',
  'Pay Now': 'अभी भुगतान करें',
  'Pay Securely →': 'सुरक्षित भुगतान →',
  'ENTER AMOUNT': 'राशि दर्ज करें',
  'Scan QR': 'क्यूआर स्कैन',
  'Align the QR code within the frame': 'क्यूआर कोड को फ़्रेम में रखें',
  'Payment Successful': 'भुगतान सफल',
  'Back to Home': 'होम पर लौटें',
  'Transaction Successful': 'लेनदेन सफल',
  'Authorising Transaction...': 'लेनदेन अधिकृत हो रहा है...',
  'Secure encryption active': 'सुरक्षित एन्क्रिप्शन सक्रिय',
  'Transaction History': 'लेनदेन इतिहास',
  'No Transactions Found': 'कोई लेनदेन नहीं मिला',
  'Bank transfer': 'बैंक हस्तांतरण',
  'Secure Ledger Transfer': 'सुरक्षित लेजर हस्तांतरण',
  'Verified by FINIX Protocol': 'फिनिक्स प्रोटोकॉल द्वारा सत्यापित',
  'Please enter a valid payment amount.': 'कृपया वैध भुगतान राशि दर्ज करें।',
  'BANK ACCOUNT NUMBER': 'बैंक खाता संख्या',
  'IFSC CODE': 'आईएफएससी कोड',
  'Recent transfers': 'हाल के हस्तांतरण',
  'No recent transfers yet': 'अभी कोई हस्तांतरण नहीं',
  'Transfer to Self': 'स्वयं को हस्तांतरण',
  'Transfer Now': 'अभी हस्तांतरित करें',
  'Between your accounts': 'आपके खातों के बीच',
  'Link a second account': 'दूसरा खाता जोड़ें',
  'Instant transfer · No charges': 'तत्काल हस्तांतरण · कोई शुल्क नहीं',
  'Recent Searches': 'हाल की खोजें',
  'Search for IFSC': 'आईएफएससी खोजें',
  'No banks found.': 'कोई बैंक नहीं मिला।',

  // ─── Accounts ─────────────────────────────────────────────────────────
  'Linked Accounts': 'जुड़े खाते',
  'Add Account': 'खाता जोड़ें',
  'No linked accounts yet': 'अभी कोई खाता नहीं जुड़ा',
  'Link a bank above to see balances here.':
      'शेष राशि देखने के लिए ऊपर बैंक जोड़ें।',
  'TOTAL COMBINED BALANCE': 'कुल संयुक्त शेष',
  '+ Link a new account': '+ नया खाता जोड़ें',
  'ACCOUNT AGGREGATOR': 'खाता एग्रीगेटर',
  'Last sync: ': 'अंतिम सिंक: ',
  'LINKED DETAILS': 'जुड़े विवरण',
  'Linking your account': 'आपका खाता जोड़ा जा रहा है',
  'successfully!': 'सफलतापूर्वक!',

  // ─── Goals ────────────────────────────────────────────────────────────
  'No goals yet': 'अभी कोई लक्ष्य नहीं',
  'Add a goal above to start tracking progress.':
      'प्रगति देखने के लिए ऊपर लक्ष्य जोड़ें।',
  'TOTAL GOAL SAVINGS': 'कुल लक्ष्य बचत',
  'Add new goal': 'नया लक्ष्य जोड़ें',
  'New Goal': 'नया लक्ष्य',
  'Create goal': 'लक्ष्य बनाएँ',
  'GOAL NAME': 'लक्ष्य का नाम',
  'TARGET AMOUNT': 'लक्ष्य राशि',
  'BY WHEN': 'कब तक',
  'Please enter a goal name.': 'कृपया लक्ष्य का नाम दर्ज करें।',
  'Add Money to Goal': 'लक्ष्य में पैसे जोड़ें',
  'Add money': 'पैसे जोड़ें',
  'Milestones': 'पड़ाव',
  'Linked sources': 'जुड़े स्रोत',
  'No contribution plan set for this goal.':
      'इस लक्ष्य के लिए कोई योगदान योजना नहीं है।',
  'Run What-If': 'क्या-अगर चलाएँ',
  'Run What-If →': 'क्या-अगर चलाएँ →',

  // ─── Portfolio, loans, insurance ──────────────────────────────────────
  'Portfolio Hub': 'पोर्टफोलियो केंद्र',
  'Manage your wealth': 'अपनी संपत्ति प्रबंधित करें',
  'TOTAL PORTFOLIO VALUE': 'कुल पोर्टफोलियो मूल्य',
  'Investments': 'निवेश',
  'Loans': 'ऋण',
  'Active loans': 'सक्रिय ऋण',
  'No active loans': 'कोई सक्रिय ऋण नहीं',
  'TOTAL OUTSTANDING': 'कुल बकाया',
  'Next payment': 'अगला भुगतान',
  'Recent EMIs': 'हाल की ईएमआई',
  'Loan Statement': 'ऋण विवरण',
  'HOME LOAN · OUTSTANDING': 'गृह ऋण · बकाया',
  'Download full statement (PDF)': 'पूरा विवरण डाउनलोड करें (पीडीएफ)',
  'Insurance': 'बीमा',
  'Your policies': 'आपकी पॉलिसियाँ',
  'No active policies': 'कोई सक्रिय पॉलिसी नहीं',
  'Coverage analysis': 'कवरेज विश्लेषण',
  'Coverage Analysis': 'कवरेज विश्लेषण',
  'Current cover': 'वर्तमान कवर',
  'Suggested cover': 'सुझाया गया कवर',
  'COVERAGE GAP': 'कवरेज अंतर',
  'Protection Report': 'सुरक्षा रिपोर्ट',
  'Full protection report →': 'पूरी सुरक्षा रिपोर्ट →',
  'FINIX PROTECTION SCORE': 'फिनिक्स सुरक्षा स्कोर',
  'File a Claim': 'दावा दर्ज करें',
  'Which policy': 'कौन सी पॉलिसी',
  'Claim type': 'दावे का प्रकार',
  'Claim amount': 'दावा राशि',
  'Submit claim': 'दावा जमा करें',
  'Upload bills & discharge summary': 'बिल व डिस्चार्ज सारांश अपलोड करें',
  'See suggested plans →': 'सुझाई गई योजनाएँ देखें →',

  // ─── Markets ──────────────────────────────────────────────────────────
  'Markets': 'बाज़ार',
  'MARKET OVERVIEW': 'बाज़ार अवलोकन',
  'YOUR PORTFOLIO TODAY': 'आज आपका पोर्टफोलियो',
  'Market pulse': 'बाज़ार की नब्ज़',
  'Market Pulse Details': 'बाज़ार नब्ज़ विवरण',
  'Sector performance': 'क्षेत्र प्रदर्शन',
  'Sector Performance': 'क्षेत्र प्रदर्शन',
  'Top movers': 'प्रमुख उतार-चढ़ाव',
  'Top Movers': 'प्रमुख उतार-चढ़ाव',
  'Market Movers': 'बाज़ार चालक',
  'Top AI insights': 'शीर्ष एआई अंतर्दृष्टि',
  'Market news': 'बाज़ार समाचार',

  // ─── Tax ──────────────────────────────────────────────────────────────
  'Tax Centre': 'कर केंद्र',
  'Old Regime': 'पुरानी व्यवस्था',
  'New Regime': 'नई व्यवस्था',
  'Old regime': 'पुरानी व्यवस्था',
  'New regime': 'नई व्यवस्था',
  'BETTER FOR YOU': 'आपके लिए बेहतर',
  'Regime Comparison': 'व्यवस्था तुलना',
  'ESTIMATED SAVING': 'अनुमानित बचत',
  'OLD REGIME': 'पुरानी व्यवस्था',
  'NEW REGIME': 'नई व्यवस्था',
  'Deduction sections': 'कटौती अनुभाग',
  'No deductions · Lower slabs': 'कोई कटौती नहीं · कम स्लैब',
  'No deductions recorded for this year':
      'इस वर्ष कोई कटौती दर्ज नहीं है',
  'Apply new regime →': 'नई व्यवस्था लागू करें →',
  'New regime applied successfully!': 'नई व्यवस्था सफलतापूर्वक लागू हुई!',
  'Add Proof': 'प्रमाण जोड़ें',
  '+ Upload a proof': '+ प्रमाण अपलोड करें',
  'Upload Proof Document': 'प्रमाण दस्तावेज़ अपलोड करें',
  'Take Photo / Scan': 'फ़ोटो लें / स्कैन करें',
  'Upload PDF / Document': 'पीडीएफ / दस्तावेज़ अपलोड करें',
  'Uploading File': 'फ़ाइल अपलोड हो रही है',
  'Uploaded successfully • verified by AI':
      'सफलतापूर्वक अपलोड • एआई द्वारा सत्यापित',

  // ─── Security ─────────────────────────────────────────────────────────
  'Security': 'सुरक्षा',
  'YOUR ACCOUNT': 'आपका खाता',
  'Protection tools': 'सुरक्षा उपकरण',
  'Protection score · ': 'सुरक्षा स्कोर · ',
  'Threats blocked · ': 'रोके गए खतरे · ',
  'Last scan · ': 'अंतिम स्कैन · ',
  'Recent activity': 'हाल की गतिविधि',
  'Security Events': 'सुरक्षा घटनाएँ',
  'Emergency Freeze': 'आपातकालीन फ्रीज़',
  'Freeze Account': 'खाता फ्रीज़ करें',
  'Activate Emergency Freeze?': 'आपातकालीन फ्रीज़ सक्रिय करें?',
  'ACCOUNT FROZEN': 'खाता फ्रीज़ किया गया',
  'Unlock with Biometrics': 'बायोमेट्रिक से अनलॉक करें',
  'Cancel — keep accounts active': 'रद्द करें — खाते सक्रिय रखें',
  'SLIDE TO FREEZE ALL': 'सभी फ्रीज़ करने के लिए स्लाइड करें',
  'WHAT HAPPENS WHEN YOU FREEZE': 'फ्रीज़ करने पर क्या होता है',
  'This will instantly halt all outgoing transactions\nacross every linked account.':
      'यह हर जुड़े खाते से सभी बाहर जाने वाले\nलेनदेन तुरंत रोक देगा।',
  'SMS Detector': 'एसएमएस डिटेक्टर',
  'Scan now': 'अभी स्कैन करें',
  'RECENT SCANS': 'हाल के स्कैन',
  'Checking latest inbox messages locally...':
      'इनबॉक्स संदेश डिवाइस पर जाँचे जा रहे हैं...',
  'No messages in your inbox to scan.':
      'स्कैन करने के लिए इनबॉक्स में कोई संदेश नहीं।',
  'FINIX Security Suite': 'फिनिक्स सुरक्षा सूट',
  'Fingerprint not recognised — nothing was changed.':
      'फ़िंगरप्रिंट पहचाना नहीं गया — कुछ नहीं बदला।',
  'Account unlocked successfully.': 'खाता सफलतापूर्वक अनलॉक हुआ।',
  'All security protections activated!': 'सभी सुरक्षा सक्रिय की गईं!',
  'Audit Logs': 'ऑडिट लॉग',
  'MERKLE-VERIFIED': 'मर्कल-सत्यापित',
  'No audit events recorded yet.': 'अभी कोई ऑडिट घटना दर्ज नहीं है।',
  'Ledger database is up to date.': 'लेजर डेटाबेस अद्यतित है।',
  'Report Fraud': 'धोखाधड़ी की रिपोर्ट',
  'Report Acknowledged': 'रिपोर्ट स्वीकृत',
  'Submit report': 'रिपोर्ट जमा करें',
  'Immediate actions taken': 'तत्काल की गई कार्रवाई',
  'What happens next': 'आगे क्या होगा',
  'Attached successfully': 'सफलतापूर्वक संलग्न',
  'Upload screenshot or receipt': 'स्क्रीनशॉट या रसीद अपलोड करें',
  'Upload Evidence File': 'साक्ष्य फ़ाइल अपलोड करें',
  'Take Photo / Screenshot': 'फ़ोटो / स्क्रीनशॉट लें',
  'Upload PDF / Statement': 'पीडीएफ / विवरण अपलोड करें',
  'Attaching Evidence': 'साक्ष्य संलग्न हो रहा है',

  // ─── Notifications ────────────────────────────────────────────────────
  'Notifications': 'सूचनाएँ',
  'All caught up!': 'सब कुछ देख लिया!',
  'No new notifications for you right now.':
      'अभी आपके लिए कोई नई सूचना नहीं है।',
  'Reset Notifications': 'सूचनाएँ रीसेट करें',

  // ─── Profile and settings ─────────────────────────────────────────────
  'Personal details': 'व्यक्तिगत विवरण',
  'Update Nominee': 'नामांकित अद्यतन करें',
  'Current nominee': 'वर्तमान नामांकित',
  'New nominee details': 'नए नामांकित का विवरण',
  'Save nominee': 'नामांकित सहेजें',
  'Select Relationship': 'संबंध चुनें',
  'KYC VERIFIED': 'केवाईसी सत्यापित',
  'Sign out': 'साइन आउट',
  'Sign out?': 'साइन आउट करें?',
  'You will need your cKYC number and PIN to sign back in.':
      'दोबारा साइन इन करने के लिए आपको सीकेवाईसी नंबर और पिन चाहिए होगा।',
  'eKYC completed': 'ई-केवाईसी पूर्ण',
  'Last profile change': 'अंतिम प्रोफ़ाइल परिवर्तन',
  'Request a correction': 'सुधार का अनुरोध करें',
  'Documents': 'दस्तावेज़',
  'No documents found': 'कोई दस्तावेज़ नहीं मिला',
  'Download all as ZIP': 'सभी ज़िप में डाउनलोड करें',
  'Help & FAQs tapped': 'सहायता',

  // ─── Sign in and eKYC ─────────────────────────────────────────────────
  'Sign in to FINIX': 'फिनिक्स में साइन इन करें',
  'Sign in': 'साइन इन',
  'New to FINIX?  ': 'फिनिक्स पर नए हैं?  ',
  'Complete eKYC': 'ई-केवाईसी पूरा करें',
  'Continue to eKYC': 'ई-केवाईसी जारी रखें',
  'Forgot PIN?': 'पिन भूल गए?',
  'API address': 'एपीआई पता',
  'Why complete eKYC?': 'ई-केवाईसी क्यों करें?',
  'Verify CKYC Number': 'सीकेवाईसी नंबर सत्यापित करें',
  'CKYC NUMBER / KIN': 'सीकेवाईसी नंबर / केआईएन',
  'Start Authentication': 'प्रमाणीकरण शुरू करें',
  'API SLOT': 'एपीआई स्लॉट',
  'Ready for bank API integration': 'बैंक एपीआई एकीकरण के लिए तैयार',
  'Your information is processed securely, only with your consent.':
      'आपकी जानकारी केवल आपकी सहमति से, सुरक्षित रूप से संसाधित होती है।',
  'eKYC Verification Completed Successfully!':
      'ई-केवाईसी सत्यापन सफलतापूर्वक पूर्ण हुआ!',
  'Your session expired. Please sign in again.':
      'आपका सत्र समाप्त हो गया। कृपया दोबारा साइन इन करें।',

  // ─── Simulation ───────────────────────────────────────────────────────
  'Run simulation': 'सिमुलेशन चलाएँ',
  'Run simulation →': 'सिमुलेशन चलाएँ →',
  'Run a simulation': 'सिमुलेशन चलाएँ',
  'Simulation Completed': 'सिमुलेशन पूर्ण',
  'Back to Simulation': 'सिमुलेशन पर लौटें',
  'Apply this change': 'यह परिवर्तन लागू करें',
  'What do you want to try?': 'आप क्या आज़माना चाहते हैं?',
  'What this changes': 'इससे क्या बदलेगा',
  'How we worked this out': 'हमने यह कैसे निकाला',
  'How this works': 'यह कैसे काम करता है',
  'Why we say this': 'हम ऐसा क्यों कहते हैं',
  'EXTRA EACH MONTH': 'हर माह अतिरिक्त',
  'FOR HOW LONG': 'कितने समय तक',
  'These are projections, not promises': 'ये अनुमान हैं, वादे नहीं',
  'Running compounding projection...': 'चक्रवृद्धि अनुमान चल रहा है...',
  'By area': 'क्षेत्र अनुसार',
  'Acknowledgement': 'पावती',

  // ─── AI assistant ─────────────────────────────────────────────────────
  'Finix AI': 'फिनिक्स एआई',
  'Ask Finix AI': 'फिनिक्स एआई से पूछें',
  'Online • Wealth Assistant': 'ऑनलाइन • संपत्ति सहायक',

  // ─── Language picker and preferences ──────────────────────────────────
  'Language': 'भाषा',
  'Choose your app language': 'अपनी ऐप भाषा चुनें',
  'The app will restart to apply your choice.':
      'आपकी पसंद लागू करने के लिए ऐप पुनः प्रारंभ होगा।',
  'Restarting to apply the new language…':
      'नई भाषा लागू करने के लिए पुनः प्रारंभ हो रहा है…',
  'Preferences': 'प्राथमिकताएँ',
  'Account': 'खाता',
  'Privacy & data': 'गोपनीयता और डेटा',
  'Support': 'सहायता',
  'Transaction limits': 'लेनदेन सीमाएँ',
  'Data sharing consents': 'डेटा साझा करने की सहमति',
  'Privacy Policy': 'गोपनीयता नीति',
  'Terms & conditions': 'नियम और शर्तें',
  'Ethical charter': 'नैतिक चार्टर',
  'Help & FAQs': 'सहायता',
  'Biometric login': 'बायोमेट्रिक लॉगिन',

  // ─── Added: navigation, settings rows and seeded goal names ──────────
  'goals': 'लक्ष्य',
  'portfolio': 'पोर्टफोलियो',
  'chat': 'चैट',
  'security': 'सुरक्षा',
  'Dashboard': 'डैशबोर्ड',
  'Scan & Pay': 'स्कैन व भुगतान',
  'Transfer': 'हस्तांतरण',
  'To Contact': 'संपर्क को',
  'To Self': 'स्वयं को',
  'Linked accounts': 'जुड़े खाते',
  'Nominees & Trust Circle': 'नामांकित व भरोसा मंडल',
  'Security Corner': 'सुरक्षा कोना',
  'Audit logs': 'ऑडिट लॉग',
  'Privacy policy': 'गोपनीयता नीति',
  'Report fraud': 'धोखाधड़ी बताएँ',
  'Data sharing': 'डेटा साझा करना',
  'Help & support': 'सहायता',
  'Name, PAN, Aadhaar, address': 'नाम, पैन, आधार, पता',
  'Risk gate, SMS scanner, emergency freeze':
      'जोखिम गेट, एसएमएस स्कैनर, आपातकालीन फ्रीज़',
  'Tamper-evident record of every action':
      'हर कार्रवाई का छेड़छाड़-रोधी रिकॉर्ड',
  'Risk alerts, goals, market digest': 'जोखिम अलर्ट, लक्ष्य, बाज़ार सार',
  'Guides, chat with support': 'गाइड, सहायता से चैट',
  'Face ID enrolled on this device': 'इस डिवाइस पर फेस आईडी दर्ज है',
  'House Down Payment': 'घर का डाउन पेमेंट',
  'Home Down Payment': 'घर का डाउन पेमेंट',
  'Emergency Fund': 'आपातकालीन कोष',
  'Europe Trip': 'यूरोप यात्रा',
  'Child Education': 'बच्चे की शिक्षा',
  'Retirement Fund': 'सेवानिवृत्ति कोष',
  'Vehicle Loan': 'वाहन ऋण',
  'Home Loan': 'गृह ऋण',
  'Ask Finix AI...': 'फिनिक्स एआई से पूछें...',
  'Microphone unavailable. Check app permissions.':
      'माइक्रोफ़ोन उपलब्ध नहीं। ऐप अनुमतियाँ जाँचें।',
  'Listening…': 'सुन रहे हैं…',
};
