/// Punjabi (Gurmukhi) translations, keyed by the English string as it appears
/// in the UI.
///
/// Same contract as [hindiStrings]: prose only. Amounts, dates, percentages and
/// account numbers stay in Latin numerals, and every screen that formats a
/// number interpolates it, so those strings never reach this map.
///
/// Gurmukhi sits slightly taller than Latin and carries above-line vowel signs,
/// so short labels are kept short — several live in bottom-nav items, pills and
/// table headers where a longer string clips rather than wraps.
const Map<String, String> punjabiStrings = {
  // ─── Navigation and common actions ────────────────────────────────────
  'Home': 'ਘਰ',
  'Goals': 'ਟੀਚੇ',
  'Portfolio': 'ਪੋਰਟਫੋਲੀਓ',
  'Insights': 'ਜਾਣਕਾਰੀ',
  'Settings': 'ਸੈਟਿੰਗਾਂ',
  'Cancel': 'ਰੱਦ ਕਰੋ',
  'Save': 'ਸੰਭਾਲੋ',
  'Done': 'ਹੋ ਗਿਆ',
  'Continue': 'ਜਾਰੀ ਰੱਖੋ',
  'Close': 'ਬੰਦ ਕਰੋ',
  'Clear': 'ਸਾਫ਼ ਕਰੋ',
  'Manage': 'ਪ੍ਰਬੰਧ',
  'Got it': 'ਸਮਝ ਗਿਆ',
  'See all': 'ਸਭ ਵੇਖੋ',
  'View all →': 'ਸਭ ਵੇਖੋ →',
  'Details →': 'ਵੇਰਵੇ →',
  'Manage →': 'ਪ੍ਰਬੰਧ →',
  'Documents →': 'ਦਸਤਾਵੇਜ਼ →',
  'Coverage →': 'ਕਵਰੇਜ →',
  'Statements →': 'ਵੇਰਵੇ →',
  'Full history →': 'ਪੂਰਾ ਇਤਿਹਾਸ →',
  'All news →': 'ਸਭ ਖ਼ਬਰਾਂ →',
  'Verified': 'ਪੁਸ਼ਟੀਸ਼ੁਦਾ',
  'VERIFIED': 'ਪੁਸ਼ਟੀਸ਼ੁਦਾ',
  'LIVE': 'ਲਾਈਵ',
  'Live': 'ਲਾਈਵ',
  'ACTIVE': 'ਸਰਗਰਮ',
  'Just now': 'ਹੁਣੇ',
  'Recent': 'ਹਾਲੀਆ',
  'TOTAL': 'ਕੁੱਲ',
  'Category': 'ਸ਼੍ਰੇਣੀ',
  'CATEGORY': 'ਸ਼੍ਰੇਣੀ',
  'Description': 'ਵੇਰਵਾ',
  'AMOUNT': 'ਰਕਮ',
  'Deposit': 'ਜਮ੍ਹਾਂ',
  'Excellent': 'ਵਧੀਆ',
  'All Clear': 'ਸਭ ਠੀਕ',
  'ON TIME': 'ਸਮੇਂ ਸਿਰ',
  'Fill': 'ਭਰੋ',
  'Log': 'ਲੌਗ',
  'Policy': 'ਪਾਲਿਸੀ',
  'Goal': 'ਟੀਚਾ',
  'SYMBOL': 'ਚਿੰਨ੍ਹ',
  'ON RECORD': 'ਰਿਕਾਰਡ ਵਿੱਚ',
  'AVAILABLE': 'ਉਪਲਬਧ',
  'REFERENCE': 'ਹਵਾਲਾ',
  'CASE ID': 'ਕੇਸ ਆਈਡੀ',
  'Evidence': 'ਸਬੂਤ',
  'Under Review': 'ਸਮੀਖਿਆ ਅਧੀਨ',
  'FINIX App': 'ਫਿਨਿਕਸ ਐਪ',
  'REPORTED ON': 'ਰਿਪੋਰਟ ਮਿਤੀ',
  'REPORTED VIA': 'ਰਿਪੋਰਟ ਜ਼ਰੀਏ',

  // ─── Dashboard ────────────────────────────────────────────────────────
  'TOTAL NET WORTH': 'ਕੁੱਲ ਸ਼ੁੱਧ ਜਾਇਦਾਦ',
  'View Portfolio': 'ਪੋਰਟਫੋਲੀਓ ਵੇਖੋ',
  'All Accounts': 'ਸਾਰੇ ਖਾਤੇ',
  'Quick Actions': 'ਤੇਜ਼ ਕਾਰਵਾਈਆਂ',
  'Quick actions': 'ਤੇਜ਼ ਕਾਰਵਾਈਆਂ',
  'Overview': 'ਸੰਖੇਪ',
  'Spent this month': 'ਇਸ ਮਹੀਨੇ ਖਰਚ',
  'No prior month': 'ਪਿਛਲਾ ਮਹੀਨਾ ਨਹੀਂ',
  'Asset Allocation': 'ਜਾਇਦਾਦ ਵੰਡ',
  'No holdings': 'ਕੋਈ ਹੋਲਡਿੰਗ ਨਹੀਂ',
  'Goals Progress': 'ਟੀਚਿਆਂ ਦੀ ਤਰੱਕੀ',
  'Credit Score': 'ਕ੍ਰੈਡਿਟ ਸਕੋਰ',
  'Upcoming commitments': 'ਆਉਣ ਵਾਲੇ ਭੁਗਤਾਨ',
  'Nothing scheduled': 'ਕੁਝ ਤੈਅ ਨਹੀਂ',
  'Protection': 'ਸੁਰੱਖਿਆ',
  'Market Snapshot': 'ਬਾਜ਼ਾਰ ਝਲਕ',
  'See full analysis': 'ਪੂਰਾ ਵਿਸ਼ਲੇਸ਼ਣ ਵੇਖੋ',
  'Recent Activity': 'ਹਾਲੀਆ ਗਤੀਵਿਧੀ',
  'FINIX INSIGHT': 'ਫਿਨਿਕਸ ਜਾਣਕਾਰੀ',
  'Health Score': 'ਸਿਹਤ ਸਕੋਰ',
  'About Health Score': 'ਸਿਹਤ ਸਕੋਰ ਬਾਰੇ',

  // ─── Payments ─────────────────────────────────────────────────────────
  'Pay Anyone': 'ਕਿਸੇ ਨੂੰ ਭੁਗਤਾਨ',
  'Pay to Contact': 'ਸੰਪਰਕ ਨੂੰ ਭੁਗਤਾਨ',
  'Pay to Merchant': 'ਵਪਾਰੀ ਨੂੰ ਭੁਗਤਾਨ',
  'Pay Now': 'ਹੁਣੇ ਭੁਗਤਾਨ ਕਰੋ',
  'Pay Securely →': 'ਸੁਰੱਖਿਅਤ ਭੁਗਤਾਨ →',
  'ENTER AMOUNT': 'ਰਕਮ ਦਰਜ ਕਰੋ',
  'Scan QR': 'ਕਿਊਆਰ ਸਕੈਨ',
  'Align the QR code within the frame': 'ਕਿਊਆਰ ਕੋਡ ਨੂੰ ਫ੍ਰੇਮ ਵਿੱਚ ਰੱਖੋ',
  'Payment Successful': 'ਭੁਗਤਾਨ ਸਫਲ',
  'Back to Home': 'ਘਰ ਵਾਪਸ',
  'Transaction Successful': 'ਲੈਣ-ਦੇਣ ਸਫਲ',
  'Authorising Transaction...': 'ਲੈਣ-ਦੇਣ ਅਧਿਕਾਰਤ ਹੋ ਰਿਹਾ ਹੈ...',
  'Secure encryption active': 'ਸੁਰੱਖਿਅਤ ਇਨਕ੍ਰਿਪਸ਼ਨ ਚਾਲੂ',
  'Transaction History': 'ਲੈਣ-ਦੇਣ ਇਤਿਹਾਸ',
  'No Transactions Found': 'ਕੋਈ ਲੈਣ-ਦੇਣ ਨਹੀਂ ਮਿਲਿਆ',
  'Bank transfer': 'ਬੈਂਕ ਤਬਾਦਲਾ',
  'Secure Ledger Transfer': 'ਸੁਰੱਖਿਅਤ ਲੈਜ਼ਰ ਤਬਾਦਲਾ',
  'Verified by FINIX Protocol': 'ਫਿਨਿਕਸ ਪ੍ਰੋਟੋਕੋਲ ਵੱਲੋਂ ਪੁਸ਼ਟੀ',
  'Please enter a valid payment amount.': 'ਕਿਰਪਾ ਕਰਕੇ ਸਹੀ ਰਕਮ ਦਰਜ ਕਰੋ।',
  'BANK ACCOUNT NUMBER': 'ਬੈਂਕ ਖਾਤਾ ਨੰਬਰ',
  'IFSC CODE': 'ਆਈਐਫਐਸਸੀ ਕੋਡ',
  'Recent transfers': 'ਹਾਲੀਆ ਤਬਾਦਲੇ',
  'No recent transfers yet': 'ਅਜੇ ਕੋਈ ਤਬਾਦਲਾ ਨਹੀਂ',
  'Transfer to Self': 'ਆਪਣੇ ਖਾਤੇ ਵਿੱਚ',
  'Transfer Now': 'ਹੁਣੇ ਤਬਾਦਲਾ ਕਰੋ',
  'Between your accounts': 'ਤੁਹਾਡੇ ਖਾਤਿਆਂ ਵਿਚਕਾਰ',
  'Link a second account': 'ਦੂਜਾ ਖਾਤਾ ਜੋੜੋ',
  'Instant transfer · No charges': 'ਤੁਰੰਤ ਤਬਾਦਲਾ · ਕੋਈ ਫ਼ੀਸ ਨਹੀਂ',
  'Recent Searches': 'ਹਾਲੀਆ ਖੋਜਾਂ',
  'Search for IFSC': 'ਆਈਐਫਐਸਸੀ ਖੋਜੋ',
  'No banks found.': 'ਕੋਈ ਬੈਂਕ ਨਹੀਂ ਮਿਲਿਆ।',

  // ─── Accounts ─────────────────────────────────────────────────────────
  'Linked Accounts': 'ਜੁੜੇ ਖਾਤੇ',
  'Add Account': 'ਖਾਤਾ ਜੋੜੋ',
  'No linked accounts yet': 'ਅਜੇ ਕੋਈ ਖਾਤਾ ਨਹੀਂ ਜੁੜਿਆ',
  'Link a bank above to see balances here.':
      'ਬਕਾਇਆ ਵੇਖਣ ਲਈ ਉੱਪਰ ਬੈਂਕ ਜੋੜੋ।',
  'TOTAL COMBINED BALANCE': 'ਕੁੱਲ ਸੰਯੁਕਤ ਬਕਾਇਆ',
  '+ Link a new account': '+ ਨਵਾਂ ਖਾਤਾ ਜੋੜੋ',
  'ACCOUNT AGGREGATOR': 'ਖਾਤਾ ਐਗਰੀਗੇਟਰ',
  'Last sync: ': 'ਆਖ਼ਰੀ ਸਿੰਕ: ',
  'LINKED DETAILS': 'ਜੁੜੇ ਵੇਰਵੇ',
  'Linking your account': 'ਤੁਹਾਡਾ ਖਾਤਾ ਜੋੜਿਆ ਜਾ ਰਿਹਾ ਹੈ',
  'successfully!': 'ਸਫਲਤਾਪੂਰਵਕ!',

  // ─── Goals ────────────────────────────────────────────────────────────
  'No goals yet': 'ਅਜੇ ਕੋਈ ਟੀਚਾ ਨਹੀਂ',
  'Add a goal above to start tracking progress.':
      'ਤਰੱਕੀ ਵੇਖਣ ਲਈ ਉੱਪਰ ਟੀਚਾ ਜੋੜੋ।',
  'TOTAL GOAL SAVINGS': 'ਕੁੱਲ ਟੀਚਾ ਬੱਚਤ',
  'Add new goal': 'ਨਵਾਂ ਟੀਚਾ ਜੋੜੋ',
  'New Goal': 'ਨਵਾਂ ਟੀਚਾ',
  'Create goal': 'ਟੀਚਾ ਬਣਾਓ',
  'GOAL NAME': 'ਟੀਚੇ ਦਾ ਨਾਂ',
  'TARGET AMOUNT': 'ਟੀਚਾ ਰਕਮ',
  'BY WHEN': 'ਕਦੋਂ ਤੱਕ',
  'Please enter a goal name.': 'ਕਿਰਪਾ ਕਰਕੇ ਟੀਚੇ ਦਾ ਨਾਂ ਦਰਜ ਕਰੋ।',
  'Add Money to Goal': 'ਟੀਚੇ ਵਿੱਚ ਪੈਸੇ ਪਾਓ',
  'Add money': 'ਪੈਸੇ ਪਾਓ',
  'Milestones': 'ਪੜਾਅ',
  'Linked sources': 'ਜੁੜੇ ਸਰੋਤ',
  'No contribution plan set for this goal.':
      'ਇਸ ਟੀਚੇ ਲਈ ਕੋਈ ਯੋਗਦਾਨ ਯੋਜਨਾ ਨਹੀਂ ਹੈ।',
  'Run What-If': 'ਕੀ-ਜੇ ਚਲਾਓ',
  'Run What-If →': 'ਕੀ-ਜੇ ਚਲਾਓ →',

  // ─── Portfolio, loans, insurance ──────────────────────────────────────
  'Portfolio Hub': 'ਪੋਰਟਫੋਲੀਓ ਕੇਂਦਰ',
  'Manage your wealth': 'ਆਪਣੀ ਦੌਲਤ ਸੰਭਾਲੋ',
  'TOTAL PORTFOLIO VALUE': 'ਕੁੱਲ ਪੋਰਟਫੋਲੀਓ ਮੁੱਲ',
  'Investments': 'ਨਿਵੇਸ਼',
  'Loans': 'ਕਰਜ਼ੇ',
  'Active loans': 'ਸਰਗਰਮ ਕਰਜ਼ੇ',
  'No active loans': 'ਕੋਈ ਸਰਗਰਮ ਕਰਜ਼ਾ ਨਹੀਂ',
  'TOTAL OUTSTANDING': 'ਕੁੱਲ ਬਕਾਇਆ',
  'Next payment': 'ਅਗਲਾ ਭੁਗਤਾਨ',
  'Recent EMIs': 'ਹਾਲੀਆ ਈਐਮਆਈ',
  'Loan Statement': 'ਕਰਜ਼ਾ ਵੇਰਵਾ',
  'HOME LOAN · OUTSTANDING': 'ਘਰ ਕਰਜ਼ਾ · ਬਕਾਇਆ',
  'Download full statement (PDF)': 'ਪੂਰਾ ਵੇਰਵਾ ਡਾਊਨਲੋਡ ਕਰੋ (ਪੀਡੀਐਫ)',
  'Insurance': 'ਬੀਮਾ',
  'Your policies': 'ਤੁਹਾਡੀਆਂ ਪਾਲਿਸੀਆਂ',
  'No active policies': 'ਕੋਈ ਸਰਗਰਮ ਪਾਲਿਸੀ ਨਹੀਂ',
  'Coverage analysis': 'ਕਵਰੇਜ ਵਿਸ਼ਲੇਸ਼ਣ',
  'Coverage Analysis': 'ਕਵਰੇਜ ਵਿਸ਼ਲੇਸ਼ਣ',
  'Current cover': 'ਮੌਜੂਦਾ ਕਵਰ',
  'Suggested cover': 'ਸੁਝਾਇਆ ਕਵਰ',
  'COVERAGE GAP': 'ਕਵਰੇਜ ਪਾੜਾ',
  'Protection Report': 'ਸੁਰੱਖਿਆ ਰਿਪੋਰਟ',
  'Full protection report →': 'ਪੂਰੀ ਸੁਰੱਖਿਆ ਰਿਪੋਰਟ →',
  'FINIX PROTECTION SCORE': 'ਫਿਨਿਕਸ ਸੁਰੱਖਿਆ ਸਕੋਰ',
  'File a Claim': 'ਦਾਅਵਾ ਦਰਜ ਕਰੋ',
  'Which policy': 'ਕਿਹੜੀ ਪਾਲਿਸੀ',
  'Claim type': 'ਦਾਅਵੇ ਦੀ ਕਿਸਮ',
  'Claim amount': 'ਦਾਅਵਾ ਰਕਮ',
  'Submit claim': 'ਦਾਅਵਾ ਜਮ੍ਹਾਂ ਕਰੋ',
  'Upload bills & discharge summary': 'ਬਿੱਲ ਤੇ ਡਿਸਚਾਰਜ ਸਾਰ ਅਪਲੋਡ ਕਰੋ',
  'See suggested plans →': 'ਸੁਝਾਈਆਂ ਯੋਜਨਾਵਾਂ ਵੇਖੋ →',

  // ─── Markets ──────────────────────────────────────────────────────────
  'Markets': 'ਬਾਜ਼ਾਰ',
  'MARKET OVERVIEW': 'ਬਾਜ਼ਾਰ ਸੰਖੇਪ',
  'YOUR PORTFOLIO TODAY': 'ਅੱਜ ਤੁਹਾਡਾ ਪੋਰਟਫੋਲੀਓ',
  'Market pulse': 'ਬਾਜ਼ਾਰ ਨਬਜ਼',
  'Market Pulse Details': 'ਬਾਜ਼ਾਰ ਨਬਜ਼ ਵੇਰਵੇ',
  'Sector performance': 'ਖੇਤਰ ਪ੍ਰਦਰਸ਼ਨ',
  'Sector Performance': 'ਖੇਤਰ ਪ੍ਰਦਰਸ਼ਨ',
  'Top movers': 'ਮੁੱਖ ਉਤਰਾਅ-ਚੜ੍ਹਾਅ',
  'Top Movers': 'ਮੁੱਖ ਉਤਰਾਅ-ਚੜ੍ਹਾਅ',
  'Market Movers': 'ਬਾਜ਼ਾਰ ਚਾਲਕ',
  'Top AI insights': 'ਮੁੱਖ ਏਆਈ ਜਾਣਕਾਰੀ',
  'Market news': 'ਬਾਜ਼ਾਰ ਖ਼ਬਰਾਂ',

  // ─── Tax ──────────────────────────────────────────────────────────────
  'Tax Centre': 'ਟੈਕਸ ਕੇਂਦਰ',
  'Old Regime': 'ਪੁਰਾਣੀ ਪ੍ਰਣਾਲੀ',
  'New Regime': 'ਨਵੀਂ ਪ੍ਰਣਾਲੀ',
  'Old regime': 'ਪੁਰਾਣੀ ਪ੍ਰਣਾਲੀ',
  'New regime': 'ਨਵੀਂ ਪ੍ਰਣਾਲੀ',
  'BETTER FOR YOU': 'ਤੁਹਾਡੇ ਲਈ ਬਿਹਤਰ',
  'Regime Comparison': 'ਪ੍ਰਣਾਲੀ ਤੁਲਨਾ',
  'ESTIMATED SAVING': 'ਅਨੁਮਾਨਿਤ ਬੱਚਤ',
  'OLD REGIME': 'ਪੁਰਾਣੀ ਪ੍ਰਣਾਲੀ',
  'NEW REGIME': 'ਨਵੀਂ ਪ੍ਰਣਾਲੀ',
  'Deduction sections': 'ਕਟੌਤੀ ਭਾਗ',
  'No deductions · Lower slabs': 'ਕੋਈ ਕਟੌਤੀ ਨਹੀਂ · ਘੱਟ ਸਲੈਬ',
  'No deductions recorded for this year':
      'ਇਸ ਸਾਲ ਕੋਈ ਕਟੌਤੀ ਦਰਜ ਨਹੀਂ ਹੈ',
  'Apply new regime →': 'ਨਵੀਂ ਪ੍ਰਣਾਲੀ ਲਾਗੂ ਕਰੋ →',
  'New regime applied successfully!': 'ਨਵੀਂ ਪ੍ਰਣਾਲੀ ਸਫਲਤਾਪੂਰਵਕ ਲਾਗੂ ਹੋਈ!',
  'Add Proof': 'ਸਬੂਤ ਜੋੜੋ',
  '+ Upload a proof': '+ ਸਬੂਤ ਅਪਲੋਡ ਕਰੋ',
  'Upload Proof Document': 'ਸਬੂਤ ਦਸਤਾਵੇਜ਼ ਅਪਲੋਡ ਕਰੋ',
  'Take Photo / Scan': 'ਫ਼ੋਟੋ ਲਓ / ਸਕੈਨ ਕਰੋ',
  'Upload PDF / Document': 'ਪੀਡੀਐਫ / ਦਸਤਾਵੇਜ਼ ਅਪਲੋਡ ਕਰੋ',
  'Uploading File': 'ਫ਼ਾਈਲ ਅਪਲੋਡ ਹੋ ਰਹੀ ਹੈ',
  'Uploaded successfully • verified by AI':
      'ਸਫਲਤਾਪੂਰਵਕ ਅਪਲੋਡ • ਏਆਈ ਵੱਲੋਂ ਪੁਸ਼ਟੀ',

  // ─── Security ─────────────────────────────────────────────────────────
  'Security': 'ਸੁਰੱਖਿਆ',
  'YOUR ACCOUNT': 'ਤੁਹਾਡਾ ਖਾਤਾ',
  'Protection tools': 'ਸੁਰੱਖਿਆ ਸੰਦ',
  'Protection score · ': 'ਸੁਰੱਖਿਆ ਸਕੋਰ · ',
  'Threats blocked · ': 'ਰੋਕੇ ਖ਼ਤਰੇ · ',
  'Last scan · ': 'ਆਖ਼ਰੀ ਸਕੈਨ · ',
  'Recent activity': 'ਹਾਲੀਆ ਗਤੀਵਿਧੀ',
  'Security Events': 'ਸੁਰੱਖਿਆ ਘਟਨਾਵਾਂ',
  'Emergency Freeze': 'ਐਮਰਜੈਂਸੀ ਫ੍ਰੀਜ਼',
  'Freeze Account': 'ਖਾਤਾ ਫ੍ਰੀਜ਼ ਕਰੋ',
  'Activate Emergency Freeze?': 'ਐਮਰਜੈਂਸੀ ਫ੍ਰੀਜ਼ ਚਾਲੂ ਕਰੀਏ?',
  'ACCOUNT FROZEN': 'ਖਾਤਾ ਫ੍ਰੀਜ਼ ਕੀਤਾ',
  'Unlock with Biometrics': 'ਬਾਇਓਮੈਟ੍ਰਿਕ ਨਾਲ ਖੋਲ੍ਹੋ',
  'Cancel — keep accounts active': 'ਰੱਦ ਕਰੋ — ਖਾਤੇ ਸਰਗਰਮ ਰੱਖੋ',
  'SLIDE TO FREEZE ALL': 'ਸਭ ਫ੍ਰੀਜ਼ ਕਰਨ ਲਈ ਸਲਾਈਡ ਕਰੋ',
  'WHAT HAPPENS WHEN YOU FREEZE': 'ਫ੍ਰੀਜ਼ ਕਰਨ ਤੇ ਕੀ ਹੁੰਦਾ ਹੈ',
  'This will instantly halt all outgoing transactions\nacross every linked account.':
      'ਇਹ ਹਰ ਜੁੜੇ ਖਾਤੇ ਤੋਂ ਸਾਰੇ ਬਾਹਰ ਜਾਣ ਵਾਲੇ\nਲੈਣ-ਦੇਣ ਤੁਰੰਤ ਰੋਕ ਦੇਵੇਗਾ।',
  'SMS Detector': 'ਐਸਐਮਐਸ ਡਿਟੈਕਟਰ',
  'Scan now': 'ਹੁਣੇ ਸਕੈਨ ਕਰੋ',
  'RECENT SCANS': 'ਹਾਲੀਆ ਸਕੈਨ',
  'Checking latest inbox messages locally...':
      'ਇਨਬਾਕਸ ਸੁਨੇਹੇ ਡਿਵਾਈਸ ਤੇ ਜਾਂਚੇ ਜਾ ਰਹੇ ਹਨ...',
  'No messages in your inbox to scan.':
      'ਸਕੈਨ ਕਰਨ ਲਈ ਇਨਬਾਕਸ ਵਿੱਚ ਕੋਈ ਸੁਨੇਹਾ ਨਹੀਂ।',
  'FINIX Security Suite': 'ਫਿਨਿਕਸ ਸੁਰੱਖਿਆ ਸੂਟ',
  'Fingerprint not recognised — nothing was changed.':
      'ਫਿੰਗਰਪ੍ਰਿੰਟ ਪਛਾਣਿਆ ਨਹੀਂ ਗਿਆ — ਕੁਝ ਨਹੀਂ ਬਦਲਿਆ।',
  'Account unlocked successfully.': 'ਖਾਤਾ ਸਫਲਤਾਪੂਰਵਕ ਖੁੱਲ੍ਹਿਆ।',
  'All security protections activated!': 'ਸਾਰੀਆਂ ਸੁਰੱਖਿਆਵਾਂ ਚਾਲੂ ਕੀਤੀਆਂ!',
  'Audit Logs': 'ਆਡਿਟ ਲੌਗ',
  'MERKLE-VERIFIED': 'ਮਰਕਲ-ਪੁਸ਼ਟੀਸ਼ੁਦਾ',
  'No audit events recorded yet.': 'ਅਜੇ ਕੋਈ ਆਡਿਟ ਘਟਨਾ ਦਰਜ ਨਹੀਂ ਹੈ।',
  'Ledger database is up to date.': 'ਲੈਜ਼ਰ ਡਾਟਾਬੇਸ ਅੱਪ ਟੂ ਡੇਟ ਹੈ।',
  'Report Fraud': 'ਧੋਖਾਧੜੀ ਦੀ ਰਿਪੋਰਟ',
  'Report Acknowledged': 'ਰਿਪੋਰਟ ਸਵੀਕਾਰ',
  'Submit report': 'ਰਿਪੋਰਟ ਜਮ੍ਹਾਂ ਕਰੋ',
  'Immediate actions taken': 'ਤੁਰੰਤ ਕੀਤੀ ਕਾਰਵਾਈ',
  'What happens next': 'ਅੱਗੇ ਕੀ ਹੋਵੇਗਾ',
  'Attached successfully': 'ਸਫਲਤਾਪੂਰਵਕ ਨੱਥੀ',
  'Upload screenshot or receipt': 'ਸਕ੍ਰੀਨਸ਼ਾਟ ਜਾਂ ਰਸੀਦ ਅਪਲੋਡ ਕਰੋ',
  'Upload Evidence File': 'ਸਬੂਤ ਫ਼ਾਈਲ ਅਪਲੋਡ ਕਰੋ',
  'Take Photo / Screenshot': 'ਫ਼ੋਟੋ / ਸਕ੍ਰੀਨਸ਼ਾਟ ਲਓ',
  'Upload PDF / Statement': 'ਪੀਡੀਐਫ / ਵੇਰਵਾ ਅਪਲੋਡ ਕਰੋ',
  'Attaching Evidence': 'ਸਬੂਤ ਨੱਥੀ ਹੋ ਰਿਹਾ ਹੈ',

  // ─── Notifications ────────────────────────────────────────────────────
  'Notifications': 'ਸੂਚਨਾਵਾਂ',
  'All caught up!': 'ਸਭ ਵੇਖ ਲਿਆ!',
  'No new notifications for you right now.':
      'ਹੁਣ ਤੁਹਾਡੇ ਲਈ ਕੋਈ ਨਵੀਂ ਸੂਚਨਾ ਨਹੀਂ ਹੈ।',
  'Reset Notifications': 'ਸੂਚਨਾਵਾਂ ਰੀਸੈਟ ਕਰੋ',

  // ─── Profile and settings ─────────────────────────────────────────────
  'Personal details': 'ਨਿੱਜੀ ਵੇਰਵੇ',
  'Update Nominee': 'ਨਾਮਜ਼ਦ ਅੱਪਡੇਟ ਕਰੋ',
  'Current nominee': 'ਮੌਜੂਦਾ ਨਾਮਜ਼ਦ',
  'New nominee details': 'ਨਵੇਂ ਨਾਮਜ਼ਦ ਦੇ ਵੇਰਵੇ',
  'Save nominee': 'ਨਾਮਜ਼ਦ ਸੰਭਾਲੋ',
  'Select Relationship': 'ਰਿਸ਼ਤਾ ਚੁਣੋ',
  'KYC VERIFIED': 'ਕੇਵਾਈਸੀ ਪੁਸ਼ਟੀਸ਼ੁਦਾ',
  'Sign out': 'ਸਾਈਨ ਆਊਟ',
  'Sign out?': 'ਸਾਈਨ ਆਊਟ ਕਰੀਏ?',
  'You will need your cKYC number and PIN to sign back in.':
      'ਦੁਬਾਰਾ ਸਾਈਨ ਇਨ ਲਈ ਤੁਹਾਨੂੰ ਸੀਕੇਵਾਈਸੀ ਨੰਬਰ ਤੇ ਪਿੰਨ ਚਾਹੀਦਾ ਹੋਵੇਗਾ।',
  'eKYC completed': 'ਈ-ਕੇਵਾਈਸੀ ਪੂਰਾ',
  'Last profile change': 'ਆਖ਼ਰੀ ਪ੍ਰੋਫ਼ਾਈਲ ਬਦਲਾਅ',
  'Request a correction': 'ਸੁਧਾਰ ਦੀ ਬੇਨਤੀ ਕਰੋ',
  'Documents': 'ਦਸਤਾਵੇਜ਼',
  'No documents found': 'ਕੋਈ ਦਸਤਾਵੇਜ਼ ਨਹੀਂ ਮਿਲਿਆ',
  'Download all as ZIP': 'ਸਭ ਜ਼ਿਪ ਵਿੱਚ ਡਾਊਨਲੋਡ ਕਰੋ',
  'Help & FAQs tapped': 'ਮਦਦ',

  // ─── Sign in and eKYC ─────────────────────────────────────────────────
  'Sign in to FINIX': 'ਫਿਨਿਕਸ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ',
  'Sign in': 'ਸਾਈਨ ਇਨ',
  'New to FINIX?  ': 'ਫਿਨਿਕਸ ਤੇ ਨਵੇਂ ਹੋ?  ',
  'Complete eKYC': 'ਈ-ਕੇਵਾਈਸੀ ਪੂਰਾ ਕਰੋ',
  'Continue to eKYC': 'ਈ-ਕੇਵਾਈਸੀ ਜਾਰੀ ਰੱਖੋ',
  'Forgot PIN?': 'ਪਿੰਨ ਭੁੱਲ ਗਏ?',
  'API address': 'ਏਪੀਆਈ ਪਤਾ',
  'Why complete eKYC?': 'ਈ-ਕੇਵਾਈਸੀ ਕਿਉਂ ਕਰੀਏ?',
  'Verify CKYC Number': 'ਸੀਕੇਵਾਈਸੀ ਨੰਬਰ ਪੁਸ਼ਟੀ ਕਰੋ',
  'CKYC NUMBER / KIN': 'ਸੀਕੇਵਾਈਸੀ ਨੰਬਰ / ਕੇਆਈਐਨ',
  'Start Authentication': 'ਪ੍ਰਮਾਣੀਕਰਨ ਸ਼ੁਰੂ ਕਰੋ',
  'API SLOT': 'ਏਪੀਆਈ ਸਲਾਟ',
  'Ready for bank API integration': 'ਬੈਂਕ ਏਪੀਆਈ ਏਕੀਕਰਨ ਲਈ ਤਿਆਰ',
  'Your information is processed securely, only with your consent.':
      'ਤੁਹਾਡੀ ਜਾਣਕਾਰੀ ਸਿਰਫ਼ ਤੁਹਾਡੀ ਸਹਿਮਤੀ ਨਾਲ, ਸੁਰੱਖਿਅਤ ਢੰਗ ਨਾਲ ਵਰਤੀ ਜਾਂਦੀ ਹੈ।',
  'eKYC Verification Completed Successfully!':
      'ਈ-ਕੇਵਾਈਸੀ ਪੁਸ਼ਟੀ ਸਫਲਤਾਪੂਰਵਕ ਪੂਰੀ ਹੋਈ!',
  'Your session expired. Please sign in again.':
      'ਤੁਹਾਡਾ ਸੈਸ਼ਨ ਖ਼ਤਮ ਹੋ ਗਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਸਾਈਨ ਇਨ ਕਰੋ।',

  // ─── Simulation ───────────────────────────────────────────────────────
  'Run simulation': 'ਸਿਮੂਲੇਸ਼ਨ ਚਲਾਓ',
  'Run simulation →': 'ਸਿਮੂਲੇਸ਼ਨ ਚਲਾਓ →',
  'Run a simulation': 'ਸਿਮੂਲੇਸ਼ਨ ਚਲਾਓ',
  'Simulation Completed': 'ਸਿਮੂਲੇਸ਼ਨ ਪੂਰਾ',
  'Back to Simulation': 'ਸਿਮੂਲੇਸ਼ਨ ਤੇ ਵਾਪਸ',
  'Apply this change': 'ਇਹ ਬਦਲਾਅ ਲਾਗੂ ਕਰੋ',
  'What do you want to try?': 'ਤੁਸੀਂ ਕੀ ਅਜ਼ਮਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?',
  'What this changes': 'ਇਸ ਨਾਲ ਕੀ ਬਦਲੇਗਾ',
  'How we worked this out': 'ਅਸੀਂ ਇਹ ਕਿਵੇਂ ਕੱਢਿਆ',
  'How this works': 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
  'Why we say this': 'ਅਸੀਂ ਇਹ ਕਿਉਂ ਕਹਿੰਦੇ ਹਾਂ',
  'EXTRA EACH MONTH': 'ਹਰ ਮਹੀਨੇ ਵਾਧੂ',
  'FOR HOW LONG': 'ਕਿੰਨੇ ਸਮੇਂ ਲਈ',
  'These are projections, not promises': 'ਇਹ ਅਨੁਮਾਨ ਹਨ, ਵਾਅਦੇ ਨਹੀਂ',
  'Running compounding projection...': 'ਚੱਕਰਵਾਧੀ ਅਨੁਮਾਨ ਚੱਲ ਰਿਹਾ ਹੈ...',
  'By area': 'ਖੇਤਰ ਅਨੁਸਾਰ',
  'Acknowledgement': 'ਪ੍ਰਵਾਨਗੀ',

  // ─── AI assistant ─────────────────────────────────────────────────────
  'Finix AI': 'ਫਿਨਿਕਸ ਏਆਈ',
  'Ask Finix AI': 'ਫਿਨਿਕਸ ਏਆਈ ਤੋਂ ਪੁੱਛੋ',
  'Online • Wealth Assistant': 'ਆਨਲਾਈਨ • ਦੌਲਤ ਸਹਾਇਕ',

  // ─── Language picker and preferences ──────────────────────────────────
  'Language': 'ਭਾਸ਼ਾ',
  'Choose your app language': 'ਆਪਣੀ ਐਪ ਭਾਸ਼ਾ ਚੁਣੋ',
  'The app will restart to apply your choice.':
      'ਤੁਹਾਡੀ ਚੋਣ ਲਾਗੂ ਕਰਨ ਲਈ ਐਪ ਮੁੜ ਚਾਲੂ ਹੋਵੇਗੀ।',
  'Restarting to apply the new language…':
      'ਨਵੀਂ ਭਾਸ਼ਾ ਲਾਗੂ ਕਰਨ ਲਈ ਮੁੜ ਚਾਲੂ ਹੋ ਰਹੀ ਹੈ…',
  'Preferences': 'ਤਰਜੀਹਾਂ',
  'Account': 'ਖਾਤਾ',
  'Privacy & data': 'ਗੋਪਨੀਯਤਾ ਤੇ ਡਾਟਾ',
  'Support': 'ਸਹਾਇਤਾ',
  'Transaction limits': 'ਲੈਣ-ਦੇਣ ਸੀਮਾਵਾਂ',
  'Data sharing consents': 'ਡਾਟਾ ਸਾਂਝਾ ਕਰਨ ਦੀ ਸਹਿਮਤੀ',
  'Privacy Policy': 'ਗੋਪਨੀਯਤਾ ਨੀਤੀ',
  'Terms & conditions': 'ਨਿਯਮ ਤੇ ਸ਼ਰਤਾਂ',
  'Ethical charter': 'ਨੈਤਿਕ ਚਾਰਟਰ',
  'Help & FAQs': 'ਮਦਦ',
  'Biometric login': 'ਬਾਇਓਮੈਟ੍ਰਿਕ ਲੌਗਇਨ',

  // ─── Added: navigation, settings rows and seeded goal names ──────────
  'goals': 'ਟੀਚੇ',
  'portfolio': 'ਪੋਰਟਫੋਲੀਓ',
  'chat': 'ਚੈਟ',
  'security': 'ਸੁਰੱਖਿਆ',
  'Dashboard': 'ਡੈਸ਼ਬੋਰਡ',
  'Scan & Pay': 'ਸਕੈਨ ਤੇ ਭੁਗਤਾਨ',
  'Transfer': 'ਤਬਾਦਲਾ',
  'To Contact': 'ਸੰਪਰਕ ਨੂੰ',
  'To Self': 'ਆਪਣੇ ਨੂੰ',
  'Linked accounts': 'ਜੁੜੇ ਖਾਤੇ',
  'Nominees & Trust Circle': 'ਨਾਮਜ਼ਦ ਤੇ ਭਰੋਸਾ ਦਾਇਰਾ',
  'Security Corner': 'ਸੁਰੱਖਿਆ ਕੋਨਾ',
  'Audit logs': 'ਆਡਿਟ ਲੌਗ',
  'Privacy policy': 'ਗੋਪਨੀਯਤਾ ਨੀਤੀ',
  'Report fraud': 'ਧੋਖਾਧੜੀ ਦੱਸੋ',
  'Data sharing': 'ਡਾਟਾ ਸਾਂਝਾ ਕਰਨਾ',
  'Help & support': 'ਮਦਦ',
  'Name, PAN, Aadhaar, address': 'ਨਾਂ, ਪੈਨ, ਆਧਾਰ, ਪਤਾ',
  'Risk gate, SMS scanner, emergency freeze':
      'ਜੋਖਮ ਗੇਟ, ਐਸਐਮਐਸ ਸਕੈਨਰ, ਐਮਰਜੈਂਸੀ ਫ੍ਰੀਜ਼',
  'Tamper-evident record of every action': 'ਹਰ ਕਾਰਵਾਈ ਦਾ ਛੇੜਛਾੜ-ਰੋਧੀ ਰਿਕਾਰਡ',
  'Risk alerts, goals, market digest': 'ਜੋਖਮ ਚੇਤਾਵਨੀ, ਟੀਚੇ, ਬਾਜ਼ਾਰ ਸਾਰ',
  'Guides, chat with support': 'ਗਾਈਡ, ਸਹਾਇਤਾ ਨਾਲ ਚੈਟ',
  'Face ID enrolled on this device': 'ਇਸ ਡਿਵਾਈਸ ਤੇ ਫੇਸ ਆਈਡੀ ਦਰਜ ਹੈ',
  'House Down Payment': 'ਘਰ ਦੀ ਡਾਊਨ ਪੇਮੈਂਟ',
  'Home Down Payment': 'ਘਰ ਦੀ ਡਾਊਨ ਪੇਮੈਂਟ',
  'Emergency Fund': 'ਐਮਰਜੈਂਸੀ ਫੰਡ',
  'Europe Trip': 'ਯੂਰਪ ਯਾਤਰਾ',
  'Child Education': 'ਬੱਚੇ ਦੀ ਸਿੱਖਿਆ',
  'Retirement Fund': 'ਸੇਵਾਮੁਕਤੀ ਫੰਡ',
  'Vehicle Loan': 'ਵਾਹਨ ਕਰਜ਼ਾ',
  'Home Loan': 'ਘਰ ਕਰਜ਼ਾ',
  'Ask Finix AI...': 'ਫਿਨਿਕਸ ਏਆਈ ਤੋਂ ਪੁੱਛੋ...',
  'Microphone unavailable. Check app permissions.':
      'ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਉਪਲਬਧ ਨਹੀਂ। ਐਪ ਇਜਾਜ਼ਤਾਂ ਜਾਂਚੋ।',
  'Listening…': 'ਸੁਣ ਰਹੇ ਹਾਂ…',
};
